services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=vault_zip

  db_test:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=vault_zip_test

  app:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=anystringanystringanystring
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=db_password
      - DB_DATABASE=vault_zip
    command: sh -c "node ace migration:run --force && node build/bin/server.js"

  tester:
    build: .
    profiles: ['test']
    depends_on:
      - db_test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TZ=UTC
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=anystringanystringanystring
      - NODE_ENV=test
      - DB_HOST=db_test
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=db_password
      - DB_DATABASE=vault_zip_test
    command: ['node', 'ace', 'test']

volumes:
  pg_data:
